# Generated by Django 2.0.3 on 2026-03-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20180510_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsCache',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payload', models.TextField(blank=True, null=True)),
                ('dirty', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
